# Base configuration
permalink: /:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
pygments: true

# Title
name: DC Open Source Playbook
subtitle:

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/DOCter'

# Author/Organization info to be displayed in the templates
author:
  name: Powered by OCTO
  url: http://octo.dc.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Play 1 - Understanding open source
  url: play1.html
  internal: true
- text: Play 2 - Adopting an internal policy on code
  url: play2.html
  internal: true
- text: Play 3 - Sharing code internally and externally
  url: play3.html
  internal: true
- text: Play 4 - Open sourcing a project
  url: play4.html
  internal: true
- text: Play 5 - Developing a community and culture
  url: play5.html
  internal: true
- text: Play 6 - Making it easy to contribute to your project
  url: play6.html
  internal: true
- text: Play 7 - Opening datasets
  url: play7.html
  internal: true
# Repo list
# List repos that you would like to appear on the homepage here
repos:

# Style Variables
brand_color: "#f4b752"
